gateway:
  routes:
    - id: post-map
      paths:
        - /pm
        - /pm1
      dest-path: /post-map
      uri: http://localhost:8080
      pci-req-paths:
        - address.zip
      pci-resp-paths:
        - address.zip
