spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://httpbin.org:80
          predicates:
            - Path=/get
          filters:
            - AddRequestHeader=X-Request-Test, foo